### ISSUE TITLE
作者你好，qq音乐的最新搜索接口已经找到

### ISSUE THREAD

**Issue by huahuadiandian** [nukemiko/MusicTagFindutils#1]
@nukemiko 你好
[这个项目](https://github.com/MCQTSS/MCQTSS_QQMusic)
经过验证，可以得到搜索结果.json
作者什么时候可以更新一下接口啊

**Comment by nukemiko** [comment]
> @nukemiko 你好 [这个项目](https://github.com/MCQTSS/MCQTSS_QQMusic) 经过验证，可以得到搜索结果.json 作者什么时候可以更新一下接口啊

正在研究怎么移植这个项目。

**Comment by huahuadiandian** [comment]
> > @nukemiko 你好 [这个项目](https://github.com/MCQTSS/MCQTSS_QQMusic) 经过验证，可以得到搜索结果.json 作者什么时候可以更新一下接口啊
> 
> 正在研究怎么移植这个项目。

```
js=resp.json()
data = js['req_0']['data']['body']['song']['list'][0]
songid = data['mid']
albumname = data['album']['name']
albumid = data['album']['mid']
singer_num = len(data['singer'])
print(songid)
print(singer_num)
for x in range(0,singer_num):
    print(data['singer'][x]['name'],data['singer'][x]['mid'])
print(albumname)
print(albumid)
```
项目中，search_music.py是最新版本的搜索功能
在其代码后添加此段代码，可以依次得到一下信息(含义请看变量名)
本机测试效果如下
```
PS D:\vscode\Python\request> Python .\search_music.py
请输入要搜索的音乐名:夜的第七章
0010ibBn4bYFTk
2
周杰伦 0025NhlN2yWrP4
潘儿 0020KRM719dcJ5
依然范特西
002jLGWe16Tf1H
```

项目中作者提供的其它众多接口大部分需要cookie，search_music.py不需要，Issue中提供了连续搜索概率失败的处理方法。
请问作者下次维护的时候，可以对该项目如何将获取的信息嵌入文件作简单介绍么，没有文档确实不是很容易阅读。😊

**Comment by 0035** [comment]
音乐信息接口报错了，坐等大佬更新

**Comment by nukemiko** [comment]
> @nukemiko 你好 [这个项目](https://github.com/MCQTSS/MCQTSS_QQMusic) 经过验证，可以得到搜索结果.json 作者什么时候可以更新一下接口啊

原项目代码使用了 `pyexecjs` 运行JS代码以生成 searchid，但由于 `pyexecjs` 已结束维护，且原项目代码可读性极差，所以在移植时把JS部分用Python重写了，经过测试之后没有发现问题。

> 请问作者下次维护的时候，可以对该项目如何将获取的信息嵌入文件作简单介绍么，没有文档确实不是很容易阅读。

目前我正在重构整个项目，考虑提供将搜索结果导出为 [`mutagen`](https://pypi.org/project/mutagen/) 兼容格式的功能，便于你直接使用 [`mutagen`](https://pypi.org/project/mutagen/) 将信息嵌入到文件。

**Comment by nukemiko** [comment]
已在开发分支中添加：https://github.com/nukemiko/MusicTagFindutils/commit/33a77e1200e0ff7acd57aaaec9f4d3e2f4cf0fcb
